# Generated by Django 6.0.3 on 2026-05-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
