# Generated by Django 6.0.3 on 2026-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portfolioprojectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('graphics_design', 'Graphics & Design'), ('programming_tech', 'Programming & Tech'), ('digital_marketing', 'Digital Marketing'), ('video_animation', 'Video & Animation'), ('writing_translation', 'Writing & Translation'), ('business', 'Business')], max_length=50),
        ),
    ]
