# Generated by Django 6.0.3 on 2026-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_freelancerprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='client_avatars/'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_categories',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
