# Generated by Django 6.0.3 on 2026-05-02 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clientprofile_about_clientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('graphics_design', 'Graphics & Design'), ('programming_tech', 'Programming & Tech'), ('digital_marketing', 'Digital Marketing'), ('video_animation', 'Video & Animation'), ('writing_translation', 'Writing & Translation'), ('business', 'Business')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
            ],
        ),
    ]
