# Generated by Django 6.0.4 on 2026-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.avif', null=True, upload_to='client_avatars/'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.avif', null=True, upload_to='freelancer_avatars/'),
        ),
    ]
