# Generated by Django 6.0.3 on 2026-05-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_clientprofile_avatar_and_more'),
        ('accounts', '0009_category_remove_freelancerprofile_category_and_more'),
    ]

    operations = [
    ]
