# Generated by Django 6.0.3 on 2026-05-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260503_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_freelancers', to='accounts.clientprofile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_clients', to='accounts.freelancerprofile')),
            ],
            options={
                'unique_together': {('client', 'freelancer')},
            },
        ),
    ]
