# Generated by Django 6.0.3 on 2026-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
