# Generated by Django 6.0.3 on 2026-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_freelancerprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='has_seen_profile_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
