# Generated by Django 6.0.3 on 2026-05-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_project_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='avatar',
        ),
    ]
