# Generated by Django 6.0.3 on 2026-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_clientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_avatars/'),
        ),
    ]
