# Generated by Django 6.0.3 on 2026-05-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_freelancerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer_avatars/'),
        ),
    ]
